### ISSUE TITLE
可以运行在h5里面吧？

### ISSUE THREAD

**Issue by octavei** [superBiuBiuMan/uni-app-wangyi#1]
这个项目非常棒。第一次学前端，不是很熟悉。像问问这个项目可以用在h5中吗？ 非常感谢！

**Comment by superBiuBiuMan** [comment]
> 这个项目非常棒。第一次学前端，不是很熟悉。像问问这个项目可以用在h5中吗？ 非常感谢！

我记得可以的,uniapp是支持编译为h5的,你可以看看这个博客https://blog.csdn.net/llall_/article/details/111664034

**Comment by octavei** [comment]
> > 这个项目非常棒。第一次学前端，不是很熟悉。像问问这个项目可以用在h5中吗？ 非常感谢！
> 
> 我记得可以的,uniapp是支持编译为h5的,你可以看看这个博客https://blog.csdn.net/llall_/article/details/111664034

学习了。非常感谢大佬。
